Repository ArjunSharda/Mathician, pull requests merged in 2022-06, with the labels that each got.

#4 Add a guide for Mathician (folder + readme.md)
  guide/readme.md
Labels: enhancement, no-coding

#5 Merge helpdownloadsandguide
  guide/help_downloads/readme_downloads.md
  guide/help_downloads/readme_upgrades.md
Labels: enhancement

#6 Update README.md (Test branch rule protection + readme update)
  README.md
Labels: enhancement, Low Priority

#7 Add logo of Mathician
  README.md
  logos/README.md
  logos/mathician_main_logo.md
Labels: enhancement, Major Priority

#8 Update logo file form
  logos/mathician_main_logo.md
  logos/mathician_main_logo.png
Labels: enhancement, Medium Priority

#9 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement, Medium Priority

#10 Create pull_request_template.md
  .github/Pull Requests/pull_request_template.md
Labels: documentation, enhancement, Medium Priority

#11 Delete .github/Pull Requests directory
  .github/Pull Requests/pull_request_template.md
Labels: Low Priority

#12 Update README.md
  README.md
Labels: enhancement, Medium Priority

#17 Update README.md (Shields.io buttons)
  README.md
Labels: documentation, enhancement, Low Priority

#18 Update bug_report.md (more information)
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, enhancement, Medium Priority

#22 Update bug_report.md (fix of issue #21)
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: bug, Medium Priority

#25 Update README.md (fixes #20)
  README.md
Labels: bug, no-coding, Minor Priority

#24 Update PULL_REQUEST_TEMPLATE.md (fixes #23)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, no-coding, Medium Priority

#26 ci(Mergify): configuration update
  .mergify.yml
Labels: enhancement, Low Priority

#27 Update dependabot.yml
  .github/dependabot.yml
Labels: enhancement, Low Priority, Dependabot

#29 Update README.md
  README.md
Labels: enhancement, no-coding, Minor Priority
